# Generated by Django 2.1.2 on 2018-10-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=1)),
                ('episode', models.IntegerField(default=1)),
                ('quality', models.TextField(default='0p')),
                ('url', models.URLField()),
                ('mediatype', models.TextField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mains.show')),
            ],
        ),
        migrations.CreateModel(
            name='website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('noof', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='videos',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mains.website'),
        ),
    ]
