# Generated by Django 3.0.4 on 2020-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(default='', max_length=300)),
                ('show', models.TextField(default='')),
                ('season', models.IntegerField(default=1)),
                ('episode', models.IntegerField(default=1)),
                ('quality', models.TextField(default='0p')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('folder', models.URLField(max_length=1000)),
            ],
        ),
    ]
