# Generated by Django 2.1.2 on 2018-10-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='mediatype',
        ),
        migrations.AlterField(
            model_name='website',
            name='noof',
            field=models.BigIntegerField(default=0),
        ),
    ]
