# Generated by Django 2.1.2 on 2018-10-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_auto_20181028_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance', models.BooleanField(default=False)),
            ],
        ),
    ]
