# Generated by Django 2.1.2 on 2018-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
